// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knbjnyiprikrskdzryzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYmpueWlwcmlrcnNrZHpyeXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mjg2ODIsImV4cCI6MjA3MjUwNDY4Mn0.POUp3d_cwx2Y6CeottfYJYWv7IoxXs2nWBUbRP7GMCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});